version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/arkecosystem/crypto
    steps:
      - checkout
      - run:
          name: Update System Dependencies
          command: sudo apt-get update
      - run:
          name: Install System Dependencies
          command: sudo apt-get install libgmp-dev
      - run:
          name: Install GMP Extension
          command: sudo docker-php-ext-install gmp && sudo docker-php-ext-enable gmp
      - run:
          name: Install BCMATH Extension
          command: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run:
          name: Update Composer
          command: sudo composer self-update
      - restore_cache:
          name: Restore Composer Package Cache
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run:
          name: Install Composer Dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          name: Save Composer Package Cache
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run Tests
          command: ./vendor/bin/phpunit
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
